# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FibonacciSeries' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FibonacciSeries

   pod  'BigInt', '~> 3.1'
end
